name: Playit RDP Tunnel

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Download and Install Playit and Cursor
      run: |
        # Download Playit
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
        
        # Download Cursor
        Invoke-WebRequest -Uri "https://downloader.cursor.sh/windows/nsis/x64" -OutFile "$env:USERPROFILE\Cursor Setup 0.43.6 - x64.exe"
        
        # Install Cursor
        Start-Process -FilePath "$env:USERPROFILE\Cursor Setup 0.43.6 - x64.exe" -ArgumentList "/S" -NoNewWindow -Wait  # /S for silent install
        
        Start-Sleep -Seconds 5  # Give some time for the installation to complete

        # Create "Cursor" folder on Desktop
        $desktopPath = [Environment]::GetFolderPath('Desktop')
        $cursorFolderPath = Join-Path -Path $desktopPath -ChildPath "Cursor"
        if (-not (Test-Path -Path $cursorFolderPath)) {
